title: Kammerensemble Neureut
markdown: kramdown
baseurl: '/kammerensemble'
permalink: /kammerensemble/blog/:year/:month/:day/:title
place: 'St. Judas Thaddäus (Neureut)'
events: 'Musik zum 4. Advent am 19. Dezember 2026'
street: ''
zipTown: ''
latitude: 48.9855557
longitude: 8.5401293
prose:
  rooturl: '_includes'
  siteurl: 'http://lieselwaeppen.github.io/kammerensemble/'
  relativeLinks: 'http://lieselwaeppen.github.io/kammerensemble/links.jsonp'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
